gh-actions: test -Ofast instead of -ffast-math
From the GCC manual page:

> Disregard strict standards compliance. -Ofast enables all -O3 optimizations.
> It also enables optimizations that are not valid for all standard-compliant
> programs. It turns on -ffast-math, -fallow-store-data-races.
> It turns off -fsemantic-interposition.

On recent clang, keep "-ffast-math" due to
> error: argument '-Ofast' is deprecated; use '-O3 -ffast-math' for the same
> behavior, or '-O3' to enable only conforming optimizations
> [-Werror,-Wdeprecated-ofast]
skipping "-O3" due to clang/llvm compiler bugs